name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]  # runs every day at 00:00 UTC
  workflow_dispatch:                  # allows manual run

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: hrnns-ti
          
          template: classic
          base: header, activity, community, repositories, metadata

          #Plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 20

          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 1
