name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1) Header + basic stats
      - name: Base metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: hrnns-ti

          filename: metrics-base.svg
          template: classic
          base: header, repositories, metadata
          config_timezone: Asia/Jakarta

      # 2) Calendar only
      - name: Contributions calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: hrnns-ti

          filename: metrics-calendar.svg
          template: classic
          base: ""
          config_timezone: Asia/Jakarta

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full

      # 3) Languages only
      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: hrnns-ti

          filename: metrics-languages.svg
          template: classic
          base: ""
          config_timezone: Asia/Jakarta

          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_threshold: 1%
          plugin_languages_limit: 20
