name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]  # runs every day at 00:00 UTC
  workflow_dispatch:                  # allows manual run

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: hrnns-ti
          
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          config_display: large
          config_padding: 0, 8   # tweak if you want more spacing
          
          # plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full

          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_threshold: 1%
          plugin_languages_limit: 20
